version: '2'
services:

  mysqldb:
    env_file: ./.env
    build:
      context: ./
      dockerfile: ./Dockerfile_DB_Dev
    container_name: ton-service-db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  be:
    depends_on:
      - mysqldb
    env_file: ./.env
    build:
      context: ./ton-service-be
      dockerfile: ./Dockerfile
    container_name: ton-service-be
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
      command: java -jar ton-service-be-1.0-SNAPSHOT.jar &
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT

  fe:
    depends_on:
      - be
    env_file: ./.env
    build:
      context: ./ton-service
      dockerfile: ./Dockerfile
    container_name: ton-service
    ports:
      - 8080:80