name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file ./ton-service-be/pom.xml

    - name: Use Node 8.x
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: npm install and npm run CI commands 
      run: |
        cd ./ton-service
        npm i
        NODE_OPTIONS=--openssl-legacy-provider npm run build
